version: "3.10"

services:
  redis:
    image: redis:7
    restart: always
    healthcheck:
      test: redis-cli ping
      interval: 5s
      timeout: 3s
      retries: 30
    volumes:
      - redis_volume:/var/lib/redis/data

  p2p-sender-signaling-server-postgres:
    image: postgres:14-alpine
    environment:
      - POSTGRES_DB=p2p-sender-signaling-server
      - POSTGRES_USER=p2p-sender-signaling-server
      - POSTGRES_HOST_AUTH_METHOD=trust
    volumes:
      - postgres_volume:/var/lib/postgresql

  signaling-server:
    depends_on:
      - p2p-sender-signaling-server-postgres
    restart: always
    build:
      context: services/signaling-server
      target: development
    volumes:
      - ./services/signaling-server:/server
    command: >
      bash -c "python manage.py migrate
      && python manage.py runserver 0.0.0.0:8000"

  web-client:
    depends_on:
      - signaling-server
    restart: always
    build:
      context: services/web-client
      target: development
    volumes:
      - /web-client/node_modules/
      - ./services/web-client:/web-client

  proxy:
    image: nginx:latest
    depends_on:
      - signaling-server
    restart: always
    volumes:
      - ./services/proxy/proxy.conf:/etc/nginx/proxy.conf
      - ./services/proxy/conf.d/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "1800:80"


volumes:
  postgres_volume:
  redis_volume: